name: Corridor
version: 1.1.1-SNAPSHOT
author: bitcash
main: gg.bitcash.corridor.Corridor
commands:
  vault:
    description: OpenVaultCommandHandler a vault.
    aliases: [pv, pvault, playervault]
#    permission: inferno.flagrate
    usage: 'Error: You did not invoke the command correctly. /vault <number|adminopen> <number>'